### ISSUE TITLE
I think this should be removed from a public repo.

### ISSUE THREAD

**Issue by CodePoetPro** [oshorefueled/socialany#1]
https://github.com/oshorefueled/socialany/blob/5a70a4063c4291b90d5ab93332dabec82749576e/db/mysqlconnect.js#L6

**Comment by oshorefueled** [comment]
Thanks, I overlooked that.

**Comment by ayomidearo** [comment]
Is this public or private?

**Comment by oshorefueled** [comment]
I made it public for some reason, Going back to private soon
